services:

  sql-db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
     - "3306:3306"
    environment:
            MYSQL_ROOT_PASSWORD: root_password_123
    
  mongodb:
    image : mongo:latest
    container_name: mongodb
    environment:
          MONGO_INITDB_ROOT_USERNAME: root  
          MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - /home/mongodb/database:/data/db
    ports:
      - "27017:27017"
    restart: always          
  
    web:
    build: ./app/
    ports:
     - "80:5000"
                   
