services:

  sql-db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
     - "3306:3306"
    environment:
            MYSQL_ROOT_PASSWORD: root_password_123
  web:
    build: ./app/
    ports:
     - "80:5000"
                   
